import type { ObservationRecord } from "./types";

/** 字段顺序，供录入表单与详情展示共用 */
export const FIELD_LABELS = {
  name: "样本名称",
  category: "样本类型",
  stain: "染色方式",
  magnification: "放大倍数",
  structure: "观察结构",
  description: "视野描述",
  conclusion: "结论",
} as const;

export const CATEGORIES = ["植物组织", "动物组织", "微生物", "血液涂片"];

const now = Date.now();

/** 已有观察记录：讲评课堂从这里挑样本 */
export const seedRecords: ObservationRecord[] = [
  {
    id: "rec-01",
    name: "洋葱表皮",
    category: "植物组织",
    stain: "碘液",
    magnification: "400x",
    structure: "细胞壁、细胞核",
    description: "表皮细胞排列紧密呈长方砖形，细胞壁清晰，细胞核被碘液染成棕黄色，可见。",
    conclusion: "典型植物保护组织，细胞核与细胞壁均可确认，建议对比动物细胞。",
    createdAt: now - 9 * 86400000,
  },
  {
    id: "rec-02",
    name: "人血涂片",
    category: "血液涂片",
    stain: "瑞氏染色",
    magnification: "1000x",
    structure: "红细胞、白细胞、血小板",
    description: "红细胞无核、双凹圆盘状，分布均匀；偶见分叶核中性粒细胞，血小板聚成小簇。",
    conclusion: "红细胞形态正常、分布均匀，未发现异常凝集，符合正常血涂片特征。",
    createdAt: now - 8 * 86400000,
  },
  {
    id: "rec-03",
    name: "草履虫",
    category: "微生物",
    stain: "活体观察",
    magnification: "200x",
    structure: "纤毛、口沟、食物泡",
    description: "虫体呈倒草鞋形，运动迅速，体表纤毛摆动明显，口沟内可见食物泡形成。",
    conclusion: "纤毛运动明显，单细胞生物运动与摄食结构观察成功。",
    createdAt: now - 7 * 86400000,
  },
  {
    id: "rec-04",
    name: "人口腔上皮细胞",
    category: "动物组织",
    stain: "亚甲基蓝",
    magnification: "400x",
    structure: "细胞膜、细胞核、细胞质",
    description: "细胞呈不规则扁平状，细胞膜边界清楚，细胞核染成蓝色，位于细胞中央。",
    conclusion: "动物细胞无细胞壁，与洋葱表皮对照可作为课堂重点。",
    createdAt: now - 6 * 86400000,
  },
  {
    id: "rec-05",
    name: "蚕豆叶下表皮",
    category: "植物组织",
    stain: "活体装片",
    magnification: "400x",
    structure: "保卫细胞、气孔、表皮细胞",
    description: "气孔由两个肾形保卫细胞围成，表皮细胞不规则嵌合，可见气孔缓慢开闭。",
    conclusion: "气孔器结构完整，保卫细胞与普通表皮细胞对比鲜明。",
    createdAt: now - 5 * 86400000,
  },
  {
    id: "rec-06",
    name: "酵母菌",
    category: "微生物",
    stain: "碘液",
    magnification: "400x",
    structure: "细胞壁、液泡、芽体",
    description: "菌体为卵圆形单细胞，部分菌体上附着较小芽体，可见出芽生殖。",
    conclusion: "出芽生殖现象普遍，单细胞真菌特征明确。",
    createdAt: now - 4 * 86400000,
  },
  {
    id: "rec-07",
    name: "蛙血涂片",
    category: "血液涂片",
    stain: "瑞氏染色",
    magnification: "400x",
    structure: "有核红细胞",
    description: "红细胞呈椭圆形，中央有明显的紫色细胞核，与人血红细胞形成鲜明对比。",
    conclusion: "红细胞有核，适合与人血涂片对比讲解脊椎动物红细胞差异。",
    createdAt: now - 3 * 86400000,
  },
  {
    id: "rec-08",
    name: "骨骼肌纵切",
    category: "动物组织",
    stain: "HE染色",
    magnification: "400x",
    structure: "横纹、肌纤维、细胞核",
    description: "肌纤维呈长圆柱状平行排列，明暗相间横纹清晰，多核位于肌膜下方。",
    conclusion: "横纹结构典型，多核长纤维为骨骼肌判定依据。",
    createdAt: now - 2 * 86400000,
  },
  {
    id: "rec-09",
    name: "水绵",
    category: "植物组织",
    stain: "活体观察",
    magnification: "100x",
    structure: "螺旋带状叶绿体、细胞横壁",
    description: "丝状体由长筒形细胞连接而成，叶绿体呈螺旋带状绕细胞内壁分布。",
    conclusion: "螺旋带状叶绿体极易辨认，适合低倍镜下整丝观察。",
    createdAt: now - 86400000,
  },
];
